# Generated by Django 4.2.2 on 2023-06-22 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploi',
            fields=[
                ('Id_exploitant', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_complet', models.CharField(max_length=100)),
                ('CIN', models.TextField()),
                ('Adresse', models.TextField(max_length=200)),
                ('Tele', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Infrac',
            fields=[
                ('Id_infraction', models.AutoField(primary_key=True, serialize=False)),
                ('Nature', models.TextField(max_length=200)),
                ('Resiliation', models.CharField(max_length=100)),
                ('Inscription_date', models.DateTimeField(blank=True, null=True)),
                ('Amende', models.CharField(max_length=100)),
                ('Emprisonement', models.CharField(max_length=100)),
                ('Id_exploitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
